// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnoOAbTeF4YyPmE2yZvc98yOeJo9e3AtA',
    appId: '1:770243415282:web:db3935babc528ac799d46b',
    messagingSenderId: '770243415282',
    projectId: 'workout-app-bitcube',
    authDomain: 'workout-app-bitcube.firebaseapp.com',
    storageBucket: 'workout-app-bitcube.firebasestorage.app',
    measurementId: 'G-2DEB9MZBVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9o6H7eMC8yl0RT_tqs6TaGPRqnJPUe2Q',
    appId: '1:770243415282:android:d350571bc608c06d99d46b',
    messagingSenderId: '770243415282',
    projectId: 'workout-app-bitcube',
    storageBucket: 'workout-app-bitcube.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApWqOCHdMUWqRhia_3rp_a6nqounvnGgI',
    appId: '1:770243415282:ios:de460d08074d2cd999d46b',
    messagingSenderId: '770243415282',
    projectId: 'workout-app-bitcube',
    storageBucket: 'workout-app-bitcube.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );
}
